[package]
name = "witx-wrapper"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
libc = "0.2.103"
witx-bindgen-rust = { git = "https://github.com/bytecodealliance/witx-bindgen.git" }
witx2 = { git = "https://github.com/bytecodealliance/witx-bindgen.git" }

[lib]
crate-type = ["staticlib", "cdylib"]

