[package]
name = "wai-me"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
libc = "0.2.103"
wai-bindgen-rust = { git = "https://github.com/bytecodealliance/wai-bindgen.git" }
parser = { git = "https://github.com/bytecodealliance/wai-bindgen.git", package="wai-parser" }

[lib]
crate-type = ["staticlib", "cdylib"]

